export const DEST_TO_DIRECTION_MAP: Record<string, 'west' | 'east'> = {
  //H
  KBWI: 'west',
  KCLE: 'west',
  KCLT: 'west',
  KCVG: 'west',
  KDCA: 'west',
  KDEN: 'west',
  KDFW: 'west',
  KDTW: 'west',
  KEWR: 'west',
  KHPN: 'west',
  KIAD: 'west',
  KJFK: 'west',
  KLGA: 'west',
  KMCO: 'west',
  KMDW: 'west',
  KMIA: 'west',
  KMSP: 'west',
  KORD: 'west',
  KPBI: 'west',
  KPHL: 'west',
  KPIT: 'west',
  KRDU: 'west',
  KRSW: 'west',
  KSRQ: 'west',
  KTPA: 'west',
  //TEC
  KACK: 'west',
  KALB: 'west',
  KBDL: 'west',
  KBDR: 'west',
  KBED: 'west',
  KBOS: 'west',
  KDXR: 'west',
  KFRG: 'west',
  KGON: 'west',
  KHFD: 'west',
  KHVN: 'west',
  KHYA: 'west',
  KISP: 'west',
  KMVY: 'west',
  KORH: 'west',
  KOWD: 'west',
  KOXC: 'west',
  KPNE: 'west',
  KPVC: 'west',
  KPVD: 'west',
  KSWF: 'west',
  //VFR
  KEEN: 'west',
  KBGR: 'east',
  KBHB: 'east',
  KLEW: 'east',
  KRKD: 'east',
};

export const DIRECTIONS = ['northeast', 'north', 'northwest', 'west', 'southwest'];

export const DEST_TO_NAME_MAP: Record<string, string> = {
  //H
  KBWI: 'Baltimore',
  KCLE: 'Cleveland',
  KCLT: 'Charlotte',
  KCVG: 'Cincinatti',
  KDCA: 'Washington Reagan',
  KDEN: 'Denver',
  KDFW: 'Dallas Fort Worth',
  KDTW: 'Detroit',
  KEWR: 'Newark',
  KHPN: 'Westchester County',
  KIAD: 'Washington Dulles',
  KJFK: 'JFK',
  KLGA: 'La Guardia',
  KMCO: 'Orlando',
  KMDW: 'Chicago Midway',
  KMIA: 'Miami',
  KMSP: 'Minneapolis',
  KORD: "Chicago O'Hare",
  KPBI: 'Palm Beach',
  KPHL: 'Philadelphia',
  KPIT: 'Pittsburgh',
  KRDU: 'Raleigh',
  KRSW: 'Fort Myers',
  KSRQ: 'Sarasota',
  KTPA: 'Tampa',
  //TEC
  KACK: 'Nantucket',
  KALB: 'Albany',
  KBDL: 'Bradley',
  KBDR: 'Stratford',
  KBED: 'Hanscom',
  KBOS: 'Boston',
  KDXR: 'Danbury',
  KFRG: 'Farmingdale',
  KGON: 'Groton',
  KHFD: 'Hartford Brainard',
  KHVN: 'New Haven',
  KHYA: 'Barnstable',
  KISP: 'Long Island',
  KMVY: "Martha's Vineyard",
  KORH: 'Worcester',
  KOWD: 'Norwood',
  KOXC: 'Oxford',
  KPNE: 'Northeast Philadelphia',
  KPVC: 'Provincetown',
  KPVD: 'Providence',
  KSWF: 'Newburgh',
  //VFR
  KEEN: 'Keene',
  KBGR: 'Bangor',
  KBHB: 'Bar Harbor',
  KLEW: 'Lewiston',
  KRKD: 'Rockland',
};

export const VFR_DESTINATIONS = [
  'KALB',
  'KBDL',
  'KBED',
  'KHVN',
  'KEEN',
  'KORH',
  'KOWD',
  'KPVD',
  'KBGR',
  'KBHB',
  'KLEW',
  'KRKD',
];
